/**
 * This class is generated by jOOQ
 */
package com.sivalabs.demo.jooq.domain;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_935ADB09_A0F0_4D1F_8413_BDD341AD1A5E</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_935ADB09_A0F0_4D1F_8413_BDD341AD1A5E = new SequenceImpl<Long>("SYSTEM_SEQUENCE_935ADB09_A0F0_4D1F_8413_BDD341AD1A5E", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_96837385_8421_4A04_9912_6EAF084324ED</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_96837385_8421_4A04_9912_6EAF084324ED = new SequenceImpl<Long>("SYSTEM_SEQUENCE_96837385_8421_4A04_9912_6EAF084324ED", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
