/**
 * This class is generated by jOOQ
 */
package com.sivalabs.demo.jooq.domain;


import com.sivalabs.demo.jooq.domain.tables.Comments;
import com.sivalabs.demo.jooq.domain.tables.Posts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.POSTS
	 */
	public static final Posts POSTS = com.sivalabs.demo.jooq.domain.tables.Posts.POSTS;

	/**
	 * The table PUBLIC.COMMENTS
	 */
	public static final Comments COMMENTS = com.sivalabs.demo.jooq.domain.tables.Comments.COMMENTS;
}
